### ISSUE TITLE
Group alike location purposes

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/myBloomington#2]
If an address  has more of one result for any category. such as an economic development zone or historic district, it should be grouped together in the same part of the screen.

**Comment by adabutch** [comment]
![Screen Shot 2019-08-08 at 4 01 26 PM](https://user-images.githubusercontent.com/2372040/62733980-ce40f380-b9f5-11e9-93c1-f0c5e4c30eab.png)

cc // @laurahaley
