### ISSUE TITLE
Add Trash pick up section on every result

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/myBloomington#3]
It would be nice to have trash info on every result even if the address doesn't get services so that there can be a link to sanitation services. Looking up trash day is one of the most widely used functions for the public.  If people think that they get trash but it isn't in the database, then they have an easy way to contact sanitation.   We could think about this for all categories not just trash

**Comment by adabutch** [comment]
If no sanitation pickup is configured for an in Bloomington jurisdiction address, I've displayed this message under the section:

> Expecting a sanitation pickup? Contact us: sanitation@bloomington.in.gov

Happy the change to whatever feels appropriate.

**Comment by laurahaley** [comment]
I can run this one by Rhea at sanitation and get her take on it.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by laurahaley** [comment]
Rhea hasn't replied. I'll try one more time then we'll just make something
up.  Do you have a test site?

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
