### ISSUE TITLE
Address - MA Mapped or Not

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/myBloomington#31]
Some addresses, in Monroe County (like Ellettsville) [could be incomplete](https://github.com/City-of-Bloomington/myBloomington/issues/30) in the data they contain causing unexpected woes.

> This is a latency effect from the fact that the person assigning address isn't the same person who maps the address.

Because of this, we need a graceful way to let the user know what's happenin' & let our front-end handle such cases accordingly.

**Comment by laurahaley** [comment]
I kinda think that the last line may be leading people astray. Soon is
relative term.   :).  Should we leave it off or come up with something that
isn't making a promise we can't fill?
Thanks for asking.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
