### ISSUE TITLE
inRoads road closings

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/myBloomington#45]
It'd be nice to display nearby road event (closing, etc) information, given a user's address search.

eg: https://bloomington.in.gov/inroads/events?format=json&start=2019-12-09&end=2019-12-10&eventTypes%5B%5D=roadClosed&eventTypes%5B%5D=localOnly&eventTypes%5B%5D=laneRestriction&eventTypes%5B%5D=reservedMeter&eventTypes%5B%5D=noisePermit&eventTypes%5B%5D=sidewalk&department_id=

**Comment by adabutch** [comment]
Appears **`inRoads`** API is busted:

**url:** https://bloomington.in.gov/inroads/events?format=json&start=2019-12-10&end=2019-12-11&eventTypes%5B%5D=roadClosed&eventTypes%5B%5D=localOnly&eventTypes%5B%5D=laneRestriction&eventTypes%5B%5D=reservedMeter&eventTypes%5B%5D=noisePermit&eventTypes%5B%5D=sidewalk

**eg:** The above URL features two important params, one for **`start`** and another for **`end`**.

**`start=2019-12-10&end=2019-12-11`**

Yet it provides a responses back w. incorrect start/end dates as seen below:

```
id: "3240",
type: "Lane Restriction",
department: { },
start: "2019-05-06",
end: "2020-08-01",
title: "321 S Walnut",
geography_description: "S Walnut street between E Smith Ave and E 3rd St",
description: "Intermittent lane closures at S Walnut street between E Smith Ave and E 3rd St excluding hours of 7:30 am-9 am and 3 pm- 6pm. The sidewalk and Bike lane will be closed for the duration of the project as well as the north south alley. The east-west alley will be limited to 12ft westbound access.",
geography: "LINESTRING(-86.53361148906325 39.16314245870467,-86.53359003139113 39.163886970604324,-86.5330106742439 39.16388281134189,-86.53301603866194 39.1628721032713)"
```

**Comment by rbdietz** [comment]
This may be providing all of the closures that are active during the period
between the start and end dates.




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
InRoads is correctly responding with the start and end times of the road closing.  It really is closd from May to to August of next year (as entered by Planning)
