### ISSUE TITLE
new council members

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/myBloomington#47]
New **`council members`** need reflected. 

(( awaiting new data ))

#### Retired - January 01, 2020:
- Dorothy Granger - `Council Vice President & District II Representative`
- Allison Chopra - `District III Representative`
- Andy Ruff - `At-Large Representative`
- Chris Sturbaum - `District I Representative`

#### Incoming - January 01, 2020:
- Kate Rosenbarger - `District I Representative`
- Sue Sgambelluri - `District II Representative`
- Ron Smith - `District III Representative`
- Matt Flaherty - `At-Large Representative`

**_notes:_**
- #32 - council member photo updates
- [geoJson](https://bloomington.in.gov/geoserver/publicgis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=publicgis:CityCouncilDistricts&maxFeatures=50&outputFormat=application%2Fjson) district boundaries

**Comment by adabutch** [comment]
Pushed 2020 updates to prod, awaiting bios/images.

**Comment by adabutch** [comment]
Note: Sue now has a headshot

**Comment by adabutch** [comment]
**_Updates for:_**
Jim Sims
Sue Sgambelluri
Isabel Piedmont Smith
Stephen Volan

**_Still needed:_**
Kate Rosenbarger
Ron Smith
Matt Flaherty

**Comment by adabutch** [comment]
**_Still needed:_**
Kate Rosenbarger
Ron Smith

**Comment by inghamn** [comment]
This information is now provided via Kubernetes values
