### ISSUE TITLE
Provide messaging for retired address or expose address status

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/myBloomington#54]
master address treats any address matches the search parameter as "valid".  In the real world, addresses and subunits that have been retired are not valid.  What makes a valid address has been a long discussion. One shouldn't be able to apply for something or get services at a address that doesn't exist anymore. We've learned that the post office has been using myB to check addresses and I imagine a lot of other agencies do to.

There may be reasons to know where these retired addresses are located and in some cases a retired address comes back to life, so perhaps we don't need to remove them completely from myB.  

I think that these updates would push people to contacting us if they think an address was retired in error.

- Add a line under the "About This Address" section for the Status.  I think the first line would be best.
- Hide  location purpose items for retired addresses that appear under the "About This Address" section such as historic districts, city council district, economic development areas,  and parking permit zones,
- Do not expose the Trash day for retired addresses

We provide some messaging  when matching as to if the address is in or out of the city and if an address has not been mapped. It would also be nice if  a message could appear when the status of the address is not Current and  there could be an additional banner placed where the  "Inside the City" check is under the map.

It may be more difficult, but if we could expose the current address in the cases were an address has been readdressed. Not all retired addresses have a current address counterpart though. Some have just been demolished or removed for some other reason.

**Comment by adabutch** [comment]
This change is wrapped up and approved by @laurahaley, will be released in 1.0.3.
